import type { Metadata } from 'next';
// import "@uploadthing/react/styles.css";
import { Inter } from 'next/font/google';
import { Inter as FontSans } from 'next/font/google';
// import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from '@/components/ui/sonner';

import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import ModalProvider from '@/components/providers/ModalProvider';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}
            <ModalProvider />
          </ThemeProvider>
          <Toaster />
        </body>
      </html>
    // </ClerkProvider>
  );
}
